#!/bin/bash
if [[ $(swaymsg -t get_tree | grep snvim | wc -c) > 0 ]]; then
   swaymsg "[app_id=snvim] scratchpad show, resize set 1880 1000"
else
   swaymsg  "exec --no-startup-id kitty --class snvim zsh -ic nvim" 
   sleep 1
   swaymsg "[app_id=snvim] scratchpad show, resize set 1880 1000"
fi
