#!/bin/bash
if [[ $(swaymsg -t get_tree | grep iamb | wc -c) > 0 ]]; then
   swaymsg "[app_id=iamb] scratchpad show, resize set 1880 1000"
else
   swaymsg  "exec --no-startup-id kitty --class iamb iamb" 
   sleep 1
   swaymsg "[app_id=iamb] scratchpad show, resize set 1880 1000"
fi
