#!/bin/bash
if [[ $(swaymsg -t get_tree | grep skitty | wc -c) > 0 ]]; then
   swaymsg "[app_id=skitty] scratchpad show, resize set 1880 1000"
else
   swaymsg  "exec --no-startup-id kitty --class skitty" 
   sleep 1
   swaymsg "[app_id=skitty] scratchpad show, resize set 1880 1000"
fi
