#!/bin/bash
if [[ $(swaymsg -t get_tree | grep "Яндекс Почта" | wc -c) > 0 ]]; then
   swaymsg '[title="Яндекс Почта"] scratchpad show, resize set 1880 1000'
else
   swaymsg  "exec --no-startup-id flatpak run org.mozilla.firefox --new-window https://mail.yandex-team.ru/" 
   sleep 1
   swaymsg '[title="Яндекс Почта"] scratchpad show, resize set 1880 1000'
fi
