github.com:
    users:
        ZenKaban:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: ZenKaban
