[pyprland]
plugins = [
    "scratchpads",
    "magnify"
]

[scratchpads.term]
command = "kitty --class scratchpad"
margin = 50
animation = "fromTop"

[scratchpads.ranger]
command = "kitty --class scratchpad -e ranger"
margin = 50

[scratchpads.btop]
command = "kitty --class scratchpad -e btop"
margin = 50

[scratchpads.disk]
command = "kitty --class scratchpad -e ncdu"
margin = 50

