[pyprland]
plugins = [
    "scratchpads",
    "magnify"
]

[scratchpads.term]
command = "kitty --class scratchpad"
margin = 50

[scratchpads.ranger]
command = "kitty --class scratchpad -e ranger"
margin = 50


