[theme]
theme = "semi-native"
[icons]
icons = "awesome4"


[[block]]
block = "focused_window"
[block.format]
full = "$title.str(max_w:90) | "
short = "$title.str(max_w:150) | "

[[block]]
block = "keyboard_layout"
driver = "sway"
format = "$layout"
[block.mappings]
"English (US)" = "EN"
"Russian (N/A)" = "RU"

# [[block]]
# block = "net"
# format = ""

# [[block]]
# block = "disk_space"
# path = "/"
# info_type = "used"
# format = "{icon} {percentage}"
# alert_absolute = true
# unit = "GB"
# alert = 50
# warning = 40

# [[block]]
# block = "memory"
# format = " $icon $mem_used.eng(prefix:Mi,w:3) "
# format_alt = " $icon_swap $swap_used_percents.eng(w:2) "
# interval = 30
# warning_mem = 70
# critical_mem = 90
#
# [[block]]
# block = "cpu"
# interval = 1
# format = " $icon $utilization /"
# format_alt = " $icon $barchart $utilization "
# # format_alt = " $icon $frequency{ $boost|} "

[[block]]
block = "sound"
driver = "pulseaudio"
format = "$icon{ $volume|}"

[[block]]
block = "battery"
format = "$percentage {$time|}"
# format = "$icon $percentage"
missing_format = ""
device = "DisplayDevice"
driver = "upower"

# [[block]]
# block = "rofication"
# interval = 1
# socket_path = "/tmp/rofi_notification_daemon"

[[block.click]]
button = "left"
cmd = "regolith-control-center sound"

[[block]]
block = "time"
interval = 5
format = "\uf073 $timestamp.datetime(f:'%a %Y-%m-%d')"

[[block]]
block = "time"
interval = 5
format = "$icon $timestamp.datetime(f:'%R')"
